@echo off
echo 🎨 Starting Wanderlust Frontend...
echo 📋 Installing dependencies...
call npm install

echo 🔧 Setting up environment...
if not exist .env (
    copy .env.example .env
)

echo 🚀 Starting React development server...
call npm start
